// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p os/exec -fake-name fake_exec
package goshim

import (
	"context"
	"os/exec"
)

//go:generate counterfeiter -o exec_fake/fake_exec.go . Exec
type Exec interface {
	Command(name string, arg ...string) *exec.Cmd
	CommandContext(ctx context.Context, name string, arg ...string) *exec.Cmd
	LookPath(file string) (string, error)
}
