// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p net/http
package goshim

import (
	"net/http"
)

//go:generate counterfeiter -o http_fake/fake_http.go . Http
type Http interface {
	Get(url string) (resp *http.Response, err error)
}
