// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p io -fake-name fake_io
package goshim

import "io"

//go:generate counterfeiter -o io_fake/fake_io.go . Io
type Io interface {
	WriteString(w io.Writer, s string) (n int, err error)
	ReadAtLeast(r io.Reader, buf []byte, min int) (n int, err error)
	ReadFull(r io.Reader, buf []byte) (n int, err error)
	CopyN(dst io.Writer, src io.Reader, n int64) (written int64, err error)
	Copy(dst io.Writer, src io.Reader) (written int64, err error)
	CopyBuffer(dst io.Writer, src io.Reader, buf []byte) (written int64, err error)
	LimitReader(r io.Reader, n int64) io.Reader
	NewSectionReader(r io.ReaderAt, off int64, n int64) *io.SectionReader
	TeeReader(r io.Reader, w io.Writer) io.Reader
	MultiReader(readers ...io.Reader) io.Reader
	MultiWriter(writers ...io.Writer) io.Writer
	Pipe() (*io.PipeReader, *io.PipeWriter)
}
