// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p archive/zip
package zipshim

import (
	"archive/zip"
	"io"
	"os"
)

type ZipShim struct{}

func (sh *ZipShim) OpenReader(name string) (*zip.ReadCloser, error) {
	return zip.OpenReader(name)
}

func (sh *ZipShim) NewReader(r io.ReaderAt, size int64) (*zip.Reader, error) {
	return zip.NewReader(r, size)
}

func (sh *ZipShim) RegisterDecompressor(method uint16, dcomp zip.Decompressor) {
	zip.RegisterDecompressor(method, dcomp)
}

func (sh *ZipShim) RegisterCompressor(method uint16, comp zip.Compressor) {
	zip.RegisterCompressor(method, comp)
}

func (sh *ZipShim) FileInfoHeader(fi os.FileInfo) (*zip.FileHeader, error) {
	return zip.FileInfoHeader(fi)
}

func (sh *ZipShim) NewWriter(w io.Writer) *zip.Writer {
	return zip.NewWriter(w)
}
