// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p io -fake-name fake_io
package ioshim

import (
	"io"
)

type IoShim struct{}

func (sh *IoShim) WriteString(w io.Writer, s string) (n int, err error) {
	return io.WriteString(w, s)
}

func (sh *IoShim) ReadAtLeast(r io.Reader, buf []byte, min int) (n int, err error) {
	return io.ReadAtLeast(r, buf, min)
}

func (sh *IoShim) ReadFull(r io.Reader, buf []byte) (n int, err error) {
	return io.ReadFull(r, buf)
}

func (sh *IoShim) CopyN(dst io.Writer, src io.Reader, n int64) (written int64, err error) {
	return io.CopyN(dst, src, n)
}

func (sh *IoShim) Copy(dst io.Writer, src io.Reader) (written int64, err error) {
	return io.Copy(dst, src)
}

func (sh *IoShim) CopyBuffer(dst io.Writer, src io.Reader, buf []byte) (written int64, err error) {
	return io.CopyBuffer(dst, src, buf)
}

func (sh *IoShim) LimitReader(r io.Reader, n int64) io.Reader {
	return io.LimitReader(r, n)
}

func (sh *IoShim) NewSectionReader(r io.ReaderAt, off int64, n int64) *io.SectionReader {
	return io.NewSectionReader(r, off, n)
}

func (sh *IoShim) TeeReader(r io.Reader, w io.Writer) io.Reader {
	return io.TeeReader(r, w)
}

func (sh *IoShim) MultiReader(readers ...io.Reader) io.Reader {
	return io.MultiReader(readers...)
}

func (sh *IoShim) MultiWriter(writers ...io.Writer) io.Writer {
	return io.MultiWriter(writers...)
}

func (sh *IoShim) Pipe() (*io.PipeReader, *io.PipeWriter) {
	return io.Pipe()
}
