// Code generated by counterfeiter. DO NOT EDIT.
// with command: counterfeiter -p os/exec -fake-name fake_exec
package execshim

import (
	"context"
	"os/exec"
)

type ExecShim struct{}

func (sh *ExecShim) Command(name string, arg ...string) *exec.Cmd {
	return exec.Command(name, arg...)
}

func (sh *ExecShim) CommandContext(ctx context.Context, name string, arg ...string) *exec.Cmd {
	return exec.CommandContext(ctx, name, arg...)
}

func (sh *ExecShim) LookPath(file string) (string, error) {
	return exec.LookPath(file)
}
